### ISSUE TITLE
Create an instance of specific type

### ISSUE THREAD

**Issue by fungi-fungi** [SINTEF-9012/cloudml#25]
Hi,

Is there is a way to create Amazon instance of specific type rather than to control amount of cores, RAM and storage?

Best regards, Iurii Tverezovskyi

**Comment by nicolasferry** [comment]
Hi Lurii,

You can try to use the attribute "providerSpecificTypeName" in the version I just pushed (commit d4339421bbd2bcd88f6ca7591a04f162cef831f4). 

Best regards.

**Comment by fungi-fungi** [comment]
Thank you a lot.

Best regard, Iurii Tverezovskyi
