### ISSUE TITLE
Question about scaleOut

### ISSUE THREAD

**Issue by fungi-fungi** [SINTEF-9012/cloudml#30]
Hello again,

I was trying to use functionality of scaleOut function from Scaler class, but I was not able to make it work. So i have a question does it work at all, or this part is still in development? And one more question, what is the idea behind your decision to not include cloudml-library.jar generation in latest version of CloudML?

Best regards, Iurii

**Comment by nicolasferry** [comment]
Hello,

Yes the scaleOut command and the concept of resourcePools are still under development but the scaleOut command should work. 

Regarding the packaging, the library is still generated but the name has changed it is available in the module called facade, either as a standalone jar: facade/target/facade-2.0-SNAPSHOT-standalone.jar
or as : facade/target/facade-SNAPSHOT.jar

Best regards,
Nicolas
