### ISSUE TITLE
After an image is created during a scale out the startCommand script should be called again

### ISSUE THREAD

**Issue by rickdesantis** [SINTEF-9012/cloudml#36]
While scaling out a machine, the tool first creates an image of the running machine and then starts the new instance using that image.

The thing is that, at least on Amazon, when creating an image of a virtual machine the service **restarts** it. This is a problem when running for example a web server which is started via a `startCommand` script, as it won't be running anymore after the reboot.

The best thing to do (in my opinion) should be calling the `stopCommand` first before creating the image and the `startCommand` right after it starts again.

A workaround is obviously messing around with the run levels of the machine, but this should be considered as a possible "bug" or "feature request" for CloudML.

**Comment by nicolasferry** [comment]
Actually I think for Amazon an option is to create a snapshot and then an image from the snapshot, this way the scaled VM is not restart and the service still running. I will try this way first.

**Comment by rickdesantis** [comment]
I've just recalled that my `startCommand` is parametric, so using the run levels won't help me very much. As of now the easiest two solutions that come to mind from the user side are:
* scaling out creating two new machines and leaving the original one as a zombie, or
* writing the scripts for the run levels with the `startCommand`
and both are very "hacky" solutions.

**Comment by nicolasferry** [comment]
I did some updates, the VM from which the image is created does not restart anymore. First a snapshot is created and then an image from this snapshot. 

Please let me know if this fix your problem.

**Comment by rickdesantis** [comment]
Yeah, thank you very much!
