### ISSUE TITLE
[UI:Shell] Storing a deployment -> information loss

### ISSUE THREAD

**Issue by boc-modaclouds** [SINTEF-9012/cloudml#52]
Hi Nicolas,

when loading a deployment in the shell and storing it back, the endpoint property of the ExternalComponent for the load balancer gets lost. Unfortunately github does not let me attach the JSONs. I will email them.

Regards,
Stepan

**Comment by nicolasferry** [comment]
Hi Stepan,

Should be fixed now ;)

Cheers,
Nicolas

**Comment by boc-modaclouds** [comment]
Confirmed with commit 38b9cd9.
