### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by fsamreen** [SINTEF-9012/cloudml#57]
**My system config:**
Apache-maven: 3.2.1, Java version 1.7.0_51, Vendor: Oracle Corporation, OS: Windows 7.

**Compilation error:** 
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.
5.1:compile (default-compile) on project codecs.kmf: Compilation failure: Compilation failure:
[ERROR] C:\...\cloudml-master\codecs\kmf\src\main
\java\org\cloudml\codecs\BridgeToKmf.java:[504,34] error: cannot find symbol
[ERROR] symbol:   method getHostname()
[ERROR] location: variable ni of type VMInstance

I have tried looking for similar errors on web but no luck. Any useful insight/help is very much appreciated.

Thanks,
Faiza

**Comment by nicolasferry** [comment]
Hi,

Thanks for opening this issue. I forgot to commit few files in the metamodel ... It should build now!

Nicolas

**Comment by fsamreen** [comment]
Hi Nicolas, 
Thanks for your reply. I am afraid, error is persistently same.
Your kind help is highly appreciated.

Faiza

**Comment by nicolasferry** [comment]
Hi,
I just tried on a brand new VM and it went fine. Have you pulled the latest version?
Nicolas

**Comment by fsamreen** [comment]
Hi Nicolas,

Thanks for your reply. Could you please share some tutorial/step-through-guide to run a simple example (any predefined example). I wonder if I am stuck in error due to lack of supporting material. I am still trying to put my head around the order of installation and actual working (through UI/if it need to be installed on local machine/Amazon/how to load my application/generate model).
 Apologies for my lack of knowledge as I am a new bee in this domain and hoping to get some support.

Regards,
Faiza

**Comment by nicolasferry** [comment]
Are you able to build now?
You can find some documentation on our wiki page: https://github.com/SINTEF-9012/cloudml/wiki.

Br,
Nicolas

**Comment by fsamreen** [comment]
Hi Nicolas,
Yes, I managed to build it, thanks for your help. Some of the links are not accessible on wiki page such as http://cloudml.org/tutorials/ and http://cloudml.org/tutorials/. In the visual demo, I can see a CloudML web editor, though my system is in a pause state after running following command:
java -jar cloudml-WebSocket.jar
What to do now? and how to build a deployment model using cloudML? 
Looking forwards to your kind reply.

Regards,
Faiza

**Comment by nicolasferry** [comment]
Hi,
Thanks for the feedback and sorry for the late replay!
I updated the links to the tutorials in the wiki page.
In order to edit CloudML models you have three options:
* Simply write a JSON file following the JSON syntax (what is in the tutorial)
* Use our textual editor: https://github.com/SINTEF-9012/cloudml-dsl
* Use our Graphical editor: a modelio plugin https://forge.modelio.org/projects/creator-4clouds/wiki/Creator4Clouds-Tutorial-CML4C
 
To deploy (and follow a deployment) you can simply open the web-based viewer: https://github.com/SINTEF-9012/cloudml/blob/master/ui/webeditor/src/main/webapp/index.html

Finally, you have some examples of deployment models here: https://github.com/SINTEF-9012/cloudml/tree/master/docs/samples

Since you do not have anymore the build failure I will close this issue. Do not hesitate to create new issues.

Best regards,
Nicolas

**Comment by fsamreen** [comment]
Dear Nicolas,
You have  been a great help. Your efforts are very much appreciated and thank you for giving a quick glimpse of steps along with supporting links.   Feel free to close the Build Failure issue.
Best Regards, Faiza 

    On Wednesday, February 7, 2018 3:05 PM, nicolasferry <notifications@github.com> wrote:
 

 Hi,
Thanks for the feedback and sorry for the late replay!
I updated the links to the tutorials in the wiki page.
In order to edit CloudML models you have three options:   
   - Simply write a JSON file following the JSON syntax (what is in the tutorial)
   - Use our textual editor: https://github.com/SINTEF-9012/cloudml-dsl
   - Use our Graphical editor: a modelio plugin https://forge.modelio.org/projects/creator-4clouds/wiki/Creator4Clouds-Tutorial-CML4C
To deploy (and follow a deployment) you can simply open the web-based viewer: https://github.com/SINTEF-9012/cloudml/blob/master/ui/webeditor/src/main/webapp/index.htmlFinally, you have some examples of deployment models here: https://github.com/SINTEF-9012/cloudml/tree/master/docs/samplesSince you do not have anymore the build failure I will close this issue. Do not hesitate to create new issues.Best regards,
Nicolas—
